config/routes.rb
Rails.application.routes.draw do
  root to:  'exams#index'
  devise_for :governments, controllers: {
    sessions:      'governments/sessions',
    passwords:     'governments/passwords',
    registrations: 'governments/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'exams/search_result'
  resources :exams do
    get 'likes', to: 'likes#checked'
  end
  
  resources :governments, only: [:index, :show]
  resources :likes, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/government.rb
class Government < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates  :name
    validates  :prefecture
    validates  :image
  end
  belongs_to :prefecture
  has_one_attached :image
  validates :prefecture_id, numericality: { other_than: 1 }
  has_many :exams, dependent: :destroy
end

app/controllers/governments/confirmations_controller.rb
# frozen_string_literal: true

class Governments::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/governments/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Governments::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/governments/passwords_controller.rb
# frozen_string_literal: true

class Governments::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/governments/registrations_controller.rb
# frozen_string_literal: true

class Governments::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/governments/sessions_controller.rb
# frozen_string_literal: true

class Governments::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/governments/unlocks_controller.rb
# frozen_string_literal: true

class Governments::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/governments_controller.rb
class GovernmentsController < ApplicationController

  def index
    @governments = Government.where(prefecture_id: params[:prefecture_id]).order("created_at ASC")
    @prefecture = Prefecture.find_by(id: params[:prefecture_id])   
  end

  def show
    @government = Government.find(params[:id])
    @exams = @government.exams
  end

end

app/helpers/governments_helper.rb
module GovernmentsHelper
end

app/views/governments/index.html.erb
<% if @governments.exists? %>
  <h2 class="page-heading"><%= @prefecture.name %>に所在する自治体</h2 >
  <div class="governments">
      <% @governments.each do |government| %>
        <div class="government">
          <a href="/governments/<%= government.id %>">
          <div class="government__name">
            <%= government.name %>
          </div>
          <div class="government__img">
            <%= image_tag government.image.variant(gravity: :center, resize:"300x200^", crop:"300x200+0+0") if government.image.attached? %>
          </div>
          </a>
        </div>
      <% end %>
  </div>
<% else %>
  <div class="governments">
    <h2 class="page-heading"><%= @prefecture.name %>で登録されている自治体はありません</h2 >
  </div>
<% end %>

app/views/governments/show.html.erb
<h2 class="page-heading"><%= " #{@government.name}が募集している職種" %></h2>
<div>
  <%= image_tag @government.image.variant(gravity: :center, resize:"300x200^", crop:"300x200+0+0") if @government.image.attached? %>
</div>
<div class="exams"> 
  <% if @exams.exists? %>
    <% @exams.each do|exam| %>
      <div class="exam">
          <a href="/exams/<%= exam.id %>">          
          <div class ="exam__info">
            <div class="exam__list">
              <%= "募集職種:#{exam.category.name}" %>
            </div>
            <div class="exam__list">
              <%= "日程:#{exam.date}"%>
            </div>
          </div>
          </a>
          <% if exam.government  == current_government %>
          <div class="exam__manage">
            <div class="exam__list">
              <%= link_to "編集", edit_exam_path(exam.id) %>
            </div>
            <div class="exam__list">
              <%= link_to "削除", exam_path(exam),method: :delete%>
            </div>
          </div>
          <% end %> 
        <div class="exam__like">
          <%= render 'likes/like', { exam: exam} %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="exam" style="border:none;">
       現在募集中の職種はありません 
    </div>
  <% end %>
</div>