config/routes.rb
Rails.application.routes.draw do
  root to:  'exams#index'
  devise_for :governments, controllers: {
    sessions:      'governments/sessions',
    passwords:     'governments/passwords',
    registrations: 'governments/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'exams/search_result'
  resources :exams do
    get 'likes', to: 'likes#checked'
  end
  
  resources :governments, only: [:index, :show]
  resources :likes, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates :date, presence: true
  validates :age, presence: true
  validates :capacity, presence: true
  validates :category_id, numericality: { other_than: 1 }

  belongs_to :category
  belongs_to :government
  has_many   :likes, dependent: :destroy
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :authenticate_government!, except: [:index, :show, :search_result]
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]
  before_action :search_exam, only: [:index, :search_result]

  def index
    if user_signed_in?
      date_format = "%Y%m%d"
      now_date = Date.today
      @age = (now_date.strftime(date_format).to_i - current_user.birth_date.strftime(date_format).to_i )/ 10000
    end
  end

  def show
  end

  def new
    @exam = Exam.new
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.save
      redirect_to government_path(@exam.government_id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exam.update(exam_params)
      redirect_to :root
    else
      render :edit
    end
  end

  def destroy
    @exam.destroy
    redirect_to :root
  end

  def search_result
    @exams = @p.result.includes(:government).order("created_at DESC")
  end

  private

  def exam_params
    params.require(:exam).permit(:category_id, :date, :age, :capacity).merge(government_id: current_government.id)
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end

  def move_to_index
    redirect_to :root unless @exam.government_id == current_government.id
  end

  def search_exam
    @p = Exam.ransack(params[:q])  # 検索オブジェクトを生成
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_area.html.erb
<div class="region" id="region-1">▶︎北海道・東北エリア</div>
<ul class="region__inner" style="display:none" id="area-1">
  <li><%= link_to "- 北海道", governments_path(prefecture_id:2) %></li>
  <li><%= link_to "- 青森県", governments_path(prefecture_id:3) %></li>
  <li><%= link_to "- 岩手県", governments_path(prefecture_id:4) %></li>
  <li><%= link_to "- 宮城県", governments_path(prefecture_id:5) %></li>
  <li><%= link_to "- 秋田県", governments_path(prefecture_id:6) %></li>
  <li><%= link_to "- 山形県", governments_path(prefecture_id:7) %></li>
  <li><%= link_to "- 福島県", governments_path(prefecture_id:8) %></li>
</ul>

<div class="region" id="region-2">▶︎関東甲信越エリア</div>
<ul class="region__inner" style="display:none" id="area-2">
  <li><%= link_to "- 茨城県", governments_path(prefecture_id:9) %></li>
  <li><%= link_to "- 栃木県", governments_path(prefecture_id:10) %></li>
  <li><%= link_to "- 群馬県", governments_path(prefecture_id:11) %></li>
  <li><%= link_to "- 埼玉県", governments_path(prefecture_id:12) %></li>
  <li><%= link_to "- 千葉県", governments_path(prefecture_id:13) %></li>
  <li><%= link_to "- 東京都", governments_path(prefecture_id:14) %></li>
  <li><%= link_to "- 神奈川県", governments_path(prefecture_id:15) %></li>
  <li><%= link_to "- 山梨県", governments_path(prefecture_id:20) %></li>
  <li><%= link_to "- 長野県", governments_path(prefecture_id:21) %></li>
</ul>

<div class="region" id="region-3">▶︎東海・北陸エリア</div>
<ul class="region__inner" style="display:none" id="area-3">
  <li><%= link_to "- 新潟県", governments_path(prefecture_id:16) %></li>
  <li><%= link_to "- 富山県", governments_path(prefecture_id:17) %></li>
  <li><%= link_to "- 石川県", governments_path(prefecture_id:18) %></li>
  <li><%= link_to "- 福井県", governments_path(prefecture_id:19) %></li>
  <li><%= link_to "- 岐阜県", governments_path(prefecture_id:22) %></li>
  <li><%= link_to "- 静岡県", governments_path(prefecture_id:23) %></li>
  <li><%= link_to "- 愛知県", governments_path(prefecture_id:24) %></li>
  <li><%= link_to "- 三重県", governments_path(prefecture_id:25) %></li>
</ul>

<div class="region" id="region-4">▶︎近畿エリア</div>
<ul class="region__inner" style="display:none" id="area-4">
  <li><%= link_to "- 滋賀県", governments_path(prefecture_id:26) %></li>
  <li><%= link_to "- 京都府", governments_path(prefecture_id:27) %></li>
  <li><%= link_to "- 大阪府", governments_path(prefecture_id:28) %></li>
  <li><%= link_to "- 兵庫県", governments_path(prefecture_id:29) %></li>
  <li><%= link_to "- 奈良県", governments_path(prefecture_id:30) %></li>
  <li><%= link_to "- 和歌山県", governments_path(prefecture_id:31) %><li>
</ul>

<div class="region" id="region-5">▶︎中国四国エリア</div>
<ul class="region__inner" style="display:none" id="area-5">
  <li><%= link_to "- 鳥取県", governments_path(prefecture_id:32) %></li>
  <li><%= link_to "- 島根県", governments_path(prefecture_id:33) %></li>
  <li><%= link_to "- 岡山県", governments_path(prefecture_id:34) %></li>
  <li><%= link_to "- 広島県", governments_path(prefecture_id:35) %></li>
  <li><%= link_to "- 山口県", governments_path(prefecture_id:36) %></li>
  <li><%= link_to "- 徳島県", governments_path(prefecture_id:37) %></li>
  <li><%= link_to "- 香川県", governments_path(prefecture_id:38) %></li>
  <li><%= link_to "- 愛媛県", governments_path(prefecture_id:39) %></li>
  <li><%= link_to "- 高知県", governments_path(prefecture_id:40) %></li>
</ul>

<div class="region" id="region-6">▶︎九州・沖縄エリア</div>
<ul class="region__inner" style="display:none" id="area-6">
  <li><%= link_to "- 福岡県", governments_path(prefecture_id:41) %></li>
  <li><%= link_to "- 佐賀県", governments_path(prefecture_id:42) %></li>
  <li><%= link_to "- 長崎県", governments_path(prefecture_id:43) %></li>
  <li><%= link_to "- 熊本県", governments_path(prefecture_id:44) %></li>
  <li><%= link_to "- 大分県", governments_path(prefecture_id:45) %></li>
  <li><%= link_to "- 宮城県", governments_path(prefecture_id:46) %></li>
  <li><%= link_to "- 鹿児島県", governments_path(prefecture_id:47) %></li>
  <li><%= link_to "- 沖縄県", governments_path(prefecture_id:48) %></li>
</ul>

app/views/exams/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/exams/_form.html.erb
<%= form_with(model:exam,local:true) do |f|%>
  <%= render 'error_messages', model: f.object %>
  <div class="field">
   <%= f.label :category_id, "職種" %><br />
   <%= f.collection_select(:category_id, Category.all, :id, :name, {}) %>
  </div>

  <div class="field">
    <%= f.label :date, "日程" %><br />
   <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2021,
                    end_year: (Time.now.year + 1),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :age, "年齢制限" %><br />
    <%= f.text_field :age %>
  </div>

    <div class="field">
    <%= f.label :capacity, "募集人数" %><br />
    <%= f.text_field :capacity %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/exams/_search.html.erb
<%= search_form_for @p, url:  exams_search_result_path do |f| %>
  <%= f.label :date_gteq, '日程' %>
  <%= f.date_field :date_gteq %> ~
  <%= f.date_field :date_lteq_end_of_day %> 
  <br>
  <%= f.label :category_id_eq, '職種' %>
  <%= f.collection_select :category_id_eq, Category.all, :id, :name,  include_blank: '指定なし' %>
  <br>
  <%= f.label :age_gteq, '年齢' %>
  <% if user_signed_in? %>
  <%= f.search_field :age_gteq, value: "#{@age}"  %> 
  <% else %>
  <%= f.search_field :age_gteq, placeholder: "ログインで自動入力" %>
  <% end %>
  <br>
  <%= f.submit '検索' %>
<% end %>

app/views/exams/edit.html.erb
    <div class="form__wrapper">
      <h2 class="page-heading">試験情報編集</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial:"form",locals: {exam: @exam}%>
    </div>

app/views/exams/index.html.erb
<div class="greeting">
  <% if user_signed_in? %>
      <%= "こんにちは、" %>
      <%= link_to "#{current_user.name}さん",like_path(current_user) %>
  <% elsif government_signed_in? %>
      <%= link_to "#{current_government.name}",government_path(current_government) %>
      <%= "でログインしています" %>
  <% end %>
</div>

<div class = "search">
  <h2  class="subheading">条件から探す</h2>
  <%= render partial:"search"%>
</div>

<div class = "area">
  <h2  class="subheading">エリア・都道府県から探す</h2>
  <%= render partial:"area"%>
</div>

app/views/exams/new.html.erb
    <div class="form__wrapper">
      <h2 class="page-heading">新規試験投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial:"form",locals: {exam: @exam}%>
    </div>

app/views/exams/search.html.erb
<h2 class="page-heading">検索結果</h2>
<div class="exams"> 
<%# 検索結果の個数で条件分岐 %>
  <% if @exams.length !=0 %>
    <% @exams.each do |exam| %>
      <div class="exam" >
      <%# リンクして試験詳細に飛べるようにする %>
        <a href="/exams/<%= exam.id %>">
        <div class="exam__inner">
          <div class="exam__info government__img">
            <%= image_tag exam.government.image.variant(gravity: :center, resize:"150x100^", crop:"150x100+0+0") if exam.government.image.attached? %>
          </div>
          <div class ="exam__info">
            <div class="exam__list">
              <%= "自治体:#{exam.government.name}" %>
            </div> 
            <div class="exam__list">
              <%= "募集職種:#{exam.category.name}" %>
            </div> 
            <div class="exam__list">
              <%= "日程:#{exam.date}" %>
            </div>
          </div>
        </div>
        </a>
        <div class="exam__like">
          <%= render 'likes/like', { exam: exam} %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="exam" style="border:none;" >
      該当する試験はありません
    </div>
  <% end %>
</div>

app/views/exams/search_result.html.erb
<h2 class="page-heading">検索結果</h2>
<div class="exams"> 
<%# 検索結果の個数で条件分岐 %>
  <% if @exams.length !=0 %>
    <% @exams.each do |exam| %>
      <div class="exam" >
      <%# リンクして試験詳細に飛べるようにする %>
        <a href="/exams/<%= exam.id %>">
        <div class="exam__inner">
          <div class="exam__info government__img">
            <%= image_tag exam.government.image.variant(gravity: :center, resize:"150x100^", crop:"150x100+0+0") if exam.government.image.attached? %>
          </div>
          <div class ="exam__info">
            <div class="exam__list">
              <%= "自治体:#{exam.government.name}" %>
            </div> 
            <div class="exam__list">
              <%= "募集職種:#{exam.category.name}" %>
            </div> 
            <div class="exam__list">
              <%= "日程:#{exam.date}" %>
            </div>
          </div>
        </div>
        </a>
        <div class="exam__like">
          <%= render 'likes/like', { exam: exam} %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="exam" style="border:none;" >
      該当する試験はありません
    </div>
  <% end %>
</div>

app/views/exams/show.html.erb
  <div class="info__img">
  <%= image_tag @exam.government.image.variant(gravity: :center, resize:"150x100^", crop:"150x100+0+0")  %>
  </div>
  <div class = "info"> 
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th  scope="col" colspan="6">試験情報</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope ="row">自治体</th>
        <td><%= @exam.government.name %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <th scope="row">職種</th>
        <td><%= @exam.category.name %></td>
        <td colspan="4"></td>
      </tr>
      <tr>
        <th scope="row">日程</th>
        <td><%= @exam.date %></td>
        <td colspan="4"></td>
      </tr>
      <tr>
        <th scope="row">年齢制限</th>
        <td><%= @exam.age %></td>
        <td colspan="4"></td>
      </tr>
      <tr>
        <th scope="row">採用人数</th>
        <td><%= @exam.capacity %></td>
        <td colspan="4"></td>
      </tr>
      <tr>
        <th scope="row">選考方法</th>
        <td>筆記試験→面接</td>
        <td colspan="4"></td>
      </tr>
    </tbody>
  </table>
</div>