config/routes.rb
Rails.application.routes.draw do
  root to:  'exams#index'
  devise_for :governments, controllers: {
    sessions:      'governments/sessions',
    passwords:     'governments/passwords',
    registrations: 'governments/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get 'exams/search_result'
  resources :exams do
    get 'likes', to: 'likes#checked'
  end
  
  resources :governments, only: [:index, :show]
  resources :likes, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    <title>公務員試験net</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="container">
        <div class="nav">
          <div class="nav__left">
            <%= link_to "公務員試験net", root_path, class: :logo %>
            <p>地方公務員を目指す人のためのWebメディア</p>
          </div>
          <%# ログインしているとき表示 %>
           <% if user_signed_in?  %>
            <div class="nav__right">
             <%= link_to "気になる", like_path(current_user), class: :nav__btn %>
              <%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: :nav__logout %>
            </div>
           <% elsif government_signed_in? %>
            <div class="nav__right">
              <%= link_to "試験情報登録", new_exam_path, class: :nav__btn %>
              <%= link_to "ログアウト", destroy_government_session_path,method: :delete, class: :nav__logout %>              
            </div>
            <%# ログインしていないとき表示 %>
          <% else %>
            <div class="nav__right"> 
              <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: :nav__btn %>
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    
    <div class ="container">
    <%= yield %>
    </div>
    
    <footer class="footer">
      <p class="copyright">Copyright © KOUMUIN SHIKEN NET All rights reserved.</p>
    </footer>

  </body>
</html>